Three dimensional model
as30606552/ComputerGraphicsProject pull request #12
Opened 2021-02-23 00:19 UTC by as30606552

Closes #5

2021-02-23 14:07 UTC, whoawhoawhoa requested changes

2021-02-23 14:07 UTC, whoawhoawhoa commented on examples/obj_parser_test.go
> +	var output *os.File
зачем объявлять так явно и раз уж так то почему не вместе?
всм 
```go
	var (
		err    error
		input  *os.File
		output *os.File
	)
```

2021-02-23 14:07 UTC, whoawhoawhoa commented on examples/obj_scanner_test.go
> +func ExampleScanner_second() {
тот что выше тогда уж `_first`?

2021-02-23 14:07 UTC, whoawhoawhoa commented on examples/obj_parser_test.go
> +		fmt.Println(elementType.Name(), " : ", element)
а в `obj_scanner_test` ты для такого же вывода используешь `fmt.Printf` - почему?

2021-02-23 14:07 UTC, whoawhoawhoa commented on examples/obj_parser_test.go
> +	var output *os.File
Это справедливо для всех файлов

2021-02-23 14:07 UTC, whoawhoawhoa commented on examples/obj_parser_test.go
> +package examples
скажу сразу - впоследствии ты от этого огребешь
писать тесты на файл в пакете, где файл не лежит - бэд практис для го
все из-за менеджмента доступа к переменным
если захочешь закрыть часть апи - отсюда протестировать не сможешь

2021-02-23 14:07 UTC, whoawhoawhoa commented on obj/constants/constants.go
> +var elementNamesMap = map[string]ElementType{
я бы назвал это не "именем" а "сокращением", "аббревиатурой", "префиксом" итд

2021-02-23 14:07 UTC, whoawhoawhoa commented on obj/constants/constants.go
> +	Vertex                ElementType = iota // Geometric vertices: v x y z [w].
объясни, какой у тебя нейминг для констант предполагается
желательно такие вещи фиксировать в рамках всего проекта - гораздо проще читать
у тебя здесь camel case, а в scanner - капс

2021-02-23 14:07 UTC, whoawhoawhoa commented on obj/constants/constants.go
> +package constants
не вижу необходимость выносить если честно

2021-02-23 14:07 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +		return err
одинаковые кейсы можно схлопнуть

2021-02-23 14:07 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
и что же
по такому огромному методу всякий раз при написании нового парсера?
выглядит слишком избыточно)

2021-02-23 14:07 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +		parser.baseParser = baseParser("impossible token was obtained when reading the Z coordinate - " + tokenType.Name())
оч много повторов строк - можно в константы

2021-02-23 14:18 UTC, as30606552 commented on examples/obj_parser_test.go
> +package examples
Это не совсем тесты, это примеры использования. Нужны по большей части для того, чтобы при проверке преподаватель мог посмотреть каким образом вызываются методы. Не предполагается, что эти тесты будут обращаться к приватным переменным.

2021-02-23 14:20 UTC, as30606552 commented on obj/constants/constants.go
> +package constants
Много кода, создаётся ощущение, что у парсера какая-то непонятная и сложная реализация.

2021-02-23 22:10 UTC, as30606552 commented on obj/constants/constants.go
> +var elementNamesMap = map[string]ElementType{
назову объявлением

2021-02-23 22:15 UTC, as30606552 commented on obj/constants/constants.go
> +	Vertex                ElementType = iota // Geometric vertices: v x y z [w].
Изменю на camel case в scanner, но в выводе оставлю капс, чтобы выделить, что слово является типом токена

2021-02-23 22:20 UTC, as30606552 commented on obj/vertex_parser.go
> +		return err
может ты не внимательно посмотрел, я не нашел одинаковых

2021-02-23 22:23 UTC, as30606552 commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
Это позволит очень точно и однозначно определить место и причину ошибки.
По сути метод содержит только огромный список различных строк, описывающий разные виды ошибок, такое часто встречается при парсинге.

2021-02-23 22:25 UTC, as30606552 commented on obj/vertex_parser.go
> +		parser.baseParser = baseParser("impossible token was obtained when reading the Z coordinate - " + tokenType.Name())
Как и с одинаковыми кейсами свитча - на самом деле они разные, просто отличие не заметно беглым взглядом

2021-02-23 23:52 UTC, as30606552 commented on examples/obj_parser_test.go
> +	var output *os.File
исправил

2021-02-23 23:52 UTC, as30606552 commented on examples/obj_scanner_test.go
> +func ExampleScanner_second() {
исправил

2021-02-23 23:52 UTC, as30606552 commented on examples/obj_parser_test.go
> +		fmt.Println(elementType.Name(), " : ", element)
исправил

2021-02-23 23:52 UTC, as30606552 commented on examples/obj_parser_test.go
> +package examples
Перенес некоторые, так будут подхватываться документацией

2021-02-23 23:53 UTC, as30606552 commented on obj/constants/constants.go
> +package constants
Вернул в парсер

2021-02-24 07:55 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +		parser.baseParser = baseParser("impossible token was obtained when reading the Z coordinate - " + tokenType.Name())
нене
я имею в виду много одинаковых префиксов, некоторые вещи можно форматированием обыграть итд

2021-02-24 07:57 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
Ну ты везде до этого воздерживался от свичей, а здесь не стал. Почему?
По идее здесь ж тоже можно что-то общее написать

2021-02-24 08:24 UTC, as30606552 commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
Потому что до этого все кейсы выполняли одинаковые действия - переводили в другое состояние. А тут помимо этого вывод ошибок, которые в каждом кейсе уникальны. Еще в некоторых случаях заполняется структура с координатами вершины, поэтому не получится обобщить до вывода ошибки и перехода в следующее состояние. Единственная альтернатива, которая приходит в голову - массив функций, но это как будто уже черезчур.

2021-02-24 08:26 UTC, as30606552 commented on obj/vertex_parser.go
> +		parser.baseParser = baseParser("impossible token was obtained when reading the Z coordinate - " + tokenType.Name())
Вся система построена вокруг эффективного и быстрого парсинга больших файлов, не хочется в обработку каждой строчки функцию форматирования добавлять.

2021-02-24 09:27 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +		parser.baseParser = baseParser("impossible token was obtained when reading the Z coordinate - " + tokenType.Name())
ну хозяин - барин)
это просто плохо масштабируется
щас добавишь еще парсеры и там везде будут похожие сообщения об ошибках
если бы ты захотел это локализовать например
то задолбался бы уже на первом парсере)
если на это пофиг - давай зарезолвлю

2021-02-24 09:32 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
есть такая идея:
у тебя есть неявная аксиома - все стейты это числа от 1 до N, причем подряд без пропусков
ты можешь чуть чуть поменять парсер, чтобы он ожидал в экшене, например, лист функций с одинаковой сигнатурой
потом брал эти функции и выполнял по очереди, тип `массив[состояние].выполнить()` 
если в списке нет обработчика (index out of bounds) - выкидывать common ошибку
что скажешь?

2021-02-24 09:33 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
тогда ты изолируешь каждый кейс в отдельную функцию, называешь их говорящими именами, а в методе `action` просто возвращаешь их цепочку
избавляешься от кейсов, улучшаешь масштабируемость и уменьшаешь связность

2021-02-24 09:41 UTC, as30606552 commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
Такой подход не даст парсеру использовать предыдущие состояния. То, что он переходит в состояния по очереди - это конкретно в этом парсере так получилось. В общем случае, парсер может из состояния 10 перепрыгивать в состояние 5 и тогда подход с последовательным выполнением функций не сработает.

2021-02-24 09:43 UTC, as30606552 commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
Можно каждый кейс свитча вынести в свой метод, потом все методы положить в массив и свитч заменить на return array[state](tokenType, token)

2021-02-24 10:20 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
да я примерно о том же
только `return array[state](tokenType, token)` настолько коммон, что можно вынести и в `obj_parser` сразу
вот я о чем

2021-02-24 10:49 UTC, as30606552 commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
Проблема в том, что кейсы свитча меняют состояние объекта иногда, то есть в массив придется методы складывать, а это в го невозможно сделать.

2021-02-24 12:25 UTC, whoawhoawhoa commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
о, правда?
типо просто функцию можно а функцию некого объекта нельзя?
в теории можно обойти интерфейсом

2021-02-24 12:27 UTC, as30606552 commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
сигнатуру конкретного объекта никак не описать

2021-02-24 12:28 UTC, as30606552 commented on obj/vertex_parser.go
> +func (parser *vertexParser) action(tokenType scanner.TokenType, state stateType, token string) stateType {
интерфейс тоже не даст сохранить состояние конкретного объекта

2021-02-24 19:01 UTC, merged