init: drawing straight lines
as30606552/ComputerGraphicsProject pull request #13
Opened 2021-02-25 14:47 UTC by colleenbawn514

#1 Test 4 does not work, it goes into an endless loop. Look, please, you can understand what's the matter. The functions themselves work.

2021-02-25 15:44 UTC, as30606552 requested changes

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +	H1 = 200
Не нашел переменных с именем W2, H2, ... Лучше избегать названий с номерами, в данном случае достаточно W, H

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +var rgb = pngimage.NewRGB(255, 255, 255)
Глобальные переменные - плохая практика. Внутри функций непонятно, где они создаются и где могут быть изменены.

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +var rgb = pngimage.NewRGB(255, 255, 255)
Лучше написать функцию, которая создает и возвращает изображение. Пусть она будет созадавать новое изображение каждому тесту, для тестов это норм.

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +}
Во всех случаях, где используется метод `SetRGBA()`, последний параметр имеет значение 255. Чтобы этого избежать написан пакет pngimage - можно использовать типы и методы оттуда (нужно использовать).
Функции, создающие изображения дефолтного вида можно прописать прямо в пакете pngimage. Функцию, создающию белое изображение, лучше называть `WhiteImage`. Напиши пару функций - для полностью белого и полностью черного изображений.

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +// Creates an all-white png image with the size W1*H1 in the examples/pictures directory.
Комментарий не совсем точный - ниаких файлов в директории на самом деле функция не создает

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +}
Плохая реализация. Тот, кто вызывает функцию, не знает, что означет число, которое она принимает. Можно было хотябы создать несколько констант с понятными именами. В этом случае можно сделать, чтобы функция принимала параметром другую функцию, при помощи которой она будет строить иозображение (ну и другие параметры, которые сейчас лежат в глобальных переменных)

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +}
x и y всегда используются в связке. Лучше написать тип Point, содержащий два поля - координаты точки. Скорее всего такой тип уже есть в какой-нибудь стандартной библиотеке.

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +}
Еще не совсем понятно почему все координаты - целые числа. В общем случае это же не так, они и приводятся к float каждый раз. Почему не изменить просто тип параметра на float64?

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +}
К другим функциям это тоже относится

2021-02-25 15:44 UTC, as30606552 commented on examples/line_library_test.go
> +	makeFile(img, "pictures/simplest_method_image.png")
Вместо `makeFile` сдесь и дальше лучше использовать метод `Save(filename)` из pngimage

2021-02-25 15:44 UTC, as30606552 commented on pngimage/image.go
> +func (img Image) Line(x0, y0, x1, y1 int, rgb RGB) Image {
Лучше так: 
```go
func (img *Image) Line(point1, point2 Point, rgb RGB) {
// ...
}
```
Когда укзатель ставится у названия типа, которому пишешь метод, этот метод может вносить изменения, которые будут видны снаружи.
Может этот момент вызывает ошибку?

2021-02-25 15:44 UTC, as30606552 commented on pngimage/image.go
> +func (img Image) Line(x0, y0, x1, y1 int, rgb RGB) Image {
Если в стандартной библиотеке нет типа двумерной, подходящего нам (два поля float64), нужно написать свой в этом пакете.

2021-02-25 15:44 UTC, as30606552 commented on pngimage/image.go
> +// of the pixel at each step and, if the value exceeds 0.5, shift the displayed pixel by one position up/down
В документации к методу лучше не писать, как он работает. Здесь нужно только что конкретно делает и что означают параметры. Комментарии про особенности реализации лучше писать внутри метода (например перед ифом: "здесь обрабатывается такое-то")

2021-02-25 15:44 UTC, as30606552 commented on pngimage/image.go
> +				y += -1
Почему не `y -= 1`?

2021-02-25 15:44 UTC, as30606552 commented on pngimage/image.go
> +	err := 0.0
Названия переменных можно выбрать понятнее.

2021-03-01 15:07 UTC, as30606552 requested changes

2021-03-01 15:07 UTC, as30606552 commented on examples/line_library_test.go
> +}
Пример для метода Брезенхема лучше перенести в пакет pngimage, а отсюда его вообще убрать

2021-03-01 15:07 UTC, as30606552 commented on examples/line_library_test.go
> +package examples
Странное название файла. Тут тестируется не библиотека, а разные методы отрисовки линий. Предлагаю building_straight_lines_test

2021-03-01 15:07 UTC, as30606552 commented on examples/image_library_test.go
> -)
Надо запустить предыдущие тесты. Скорее всего строятся теперь маленькие картинки белого, черного, красного и градиентного цветов. Это происходит из-за того, что все файлы находятся в одном пакете и объявления у них общие. Придется отказаться от объявления глобальных констант и перенести их в методы. Здесь нужно в каждом из методов объявить константы, которые были удалены, а в твоем файле заменить глобальное объявление так же на объявление в каждом методе одинаковых констант.

2021-03-01 15:07 UTC, as30606552 commented on examples/line_library_test.go
> +	y0 = 100 //The coordinate of the origin point for drawing a star (by Y)
Будем использовать такой стиль комментариев: после двух слешей пробел, затем текст с большой буквы, в конце предложения точка (в том числе в конце всего коментария). Используй шорткат идеи для форматирования: `ctrl+alt+L` (точки это не вставит, но отступы красивые добавит).

2021-03-01 15:07 UTC, as30606552 commented on examples/line_library_test.go
> +	H = 200 //Image height
Почему тут Width с большой буквы, а height с маленькой?

2021-03-01 15:07 UTC, as30606552 commented on pngimage/image.go
> +func (img *Image) Line(point1, point2 image.Point, rgb RGB) Image {
Этот метод не должен возвращать значение, только менять изображение, у которого он вызывается

2021-03-01 15:07 UTC, as30606552 commented on examples/line_library_test.go
> +	fmt.Println("Ok")
Этот пример должен быть не здесь, а в пакете pngimage

2021-03-01 15:07 UTC, as30606552 commented on examples/line_library_test.go
> +}
Лучше заменить свитч на прямую передачу функции отрисовки линии в функцию отрисовки звезды. Например так:
```go
type drawingStraightLine func(point1, point2 image.Point, img pngimage.Image, rgb pngimage.RGB)

func StarLine(method drawingStraightLine, img pngimage.Image, rgb pngimage.RGB)
```

2021-03-01 15:07 UTC, as30606552 commented on examples/line_library_test.go
> +func StarLine(nameMethod string, img pngimage.Image, rgb pngimage.RGB) {
Лучше сделать функцию приватной, это определяется названием, с маленькой буквы - приватные функции: `starLine`

2021-03-01 15:07 UTC, as30606552 commented on pngimage/image.go
> +}
Лучше сразу работать с собственными типами. Вместо `NewRGBA` `NewImage(width, height)`, далее `img.Set(i,j,NewRGB(r,g,b))`

2021-03-01 15:07 UTC, as30606552 commented on pngimage/image.go
> +}
А в конце `return img`

2021-03-01 15:07 UTC, as30606552 commented on pngimage/image.go
> +//Returns the picture from the drawn line.
Можно тут добавить, что используется алгоритм Брезенхема

2021-03-01 15:39 UTC, colleenbawn514 commented on examples/line_library_test.go
> +}
А куда его перенести к примеру?

2021-03-01 15:45 UTC, as30606552 commented on examples/line_library_test.go
> +}
создай файл image_test в пакете pngimage и перенеси туда

2021-03-01 15:46 UTC, as30606552 commented on examples/line_library_test.go
> +}
там можно будет кстати использовать приватные функции пакета, но тебе это вроде не понадобится

2021-03-01 16:24 UTC, colleenbawn514 commented on examples/line_library_test.go
> +}
Если я перенесу в другой файл, то не получится использовать приватную функцию starLine. Или не переносить, или не делать приватной. Но я за то, чтобы не переносить, потому что нам потом этот тест будет не нужен в будущем

2021-03-01 16:26 UTC, colleenbawn514 commented on pngimage/image.go
> +	err := 0.0
А как их менять, если они из лекций с его примера?

2021-03-01 16:45 UTC, as30606552 commented on pngimage/image.go
> +	err := 0.0
Переменные совсем не обязательно называть как в примере из лекций. Это же пример

2021-03-01 16:50 UTC, as30606552 commented on examples/line_library_test.go
> +}
Предлагаю скопировать функцию `starLine` в этот тест и перенести все же. Тесты нужны по двум причинам:
1. При изменении кода можно будет в любой момент прогнать тесты и узнать, не испортился ли старый функционал.
2. Это не просто тесты, а тесты-примеры. Например если в GoLand нажать на функцию, а потом нажать `ctrl+Q`, отобразится документация функции. Если пример объявлен в том же покете, он появится в этой документации как пример использования.

2021-03-05 20:07 UTC, as30606552 requested changes

2021-03-05 20:07 UTC, as30606552 commented on examples/building_straight_lines_test.go
> +	var H = 200 // Image Height.
Вроде бы нет смысла теперь объявлять переменные вообще, можно сразу `pngimage.WhiteImage(200,200)`

2021-03-05 20:07 UTC, as30606552 commented on pngimage/image.go
> -func WhiteImage(width, height  int) *Image {
можно сразу задать параметрам тип `uint` и не приводить типы

2021-03-05 20:07 UTC, as30606552 commented on pngimage/image.go
> +// Create a line by Bresenham algorithm.
Не создает, а отрисовывает

2021-03-05 20:07 UTC, as30606552 commented on pngimage/image_test.go
> +func starLine(method drawingStraightLine, img Image, rgb RGB) {
Функция вызывается один раз, можно объединить с функцией примера

2021-03-05 20:07 UTC, as30606552 commented on pngimage/image_test.go
> +	y0 = 100 // The coordinate of the origin point for drawing a star (by Y).
Тоже используется только в одном месте, нет смысла создавать константы

2021-03-05 20:07 UTC, as30606552 commented on pngimage/image_test.go
> +}
Не нужно оборачивать метод функцией, нужно написать пример именно для метода. Название примера будет выглядеть так: `ExampleImage_Line`

2021-03-05 20:07 UTC, as30606552 commented on examples/building_straight_lines_test.go
> +	y0 = 100 // The coordinate of the origin point for drawing a star (by Y).
И эти константы тоже используются только один раз вроде

2021-03-05 20:07 UTC, as30606552 commented on examples/building_straight_lines_test.go
> +func starLine(method drawingStraightLine, img pngimage.Image, rgb pngimage.RGB) {
Можно принимать указатель на изображение и цвет здесь и в `drawingStraightLine`. Это позволит избежать лишнего копирования и разыменования при вызове функции.

2021-03-21 20:52 UTC, colleenbawn514 commented on pngimage/image.go
> -func WhiteImage(width, height  int) *Image {
![image](https://user-images.githubusercontent.com/49654450/111920497-cb9af100-8aa8-11eb-80b7-1876c5895543.png)
А для сравнения i привести или w и h привести?

2021-03-21 21:08 UTC, colleenbawn514 commented on pngimage/image.go
> -func WhiteImage(width, height  int) *Image {
Тип просто там потом все равно к интам приводить, да и смысла мало в том что он беззнаковый

2021-03-21 21:23 UTC, colleenbawn514 commented on examples/building_straight_lines_test.go
> +	var H = 200 // Image Height.
сделала

2021-03-21 21:23 UTC, colleenbawn514 commented on pngimage/image.go
> +// Create a line by Bresenham algorithm.
сделала

2021-03-21 21:23 UTC, colleenbawn514 commented on pngimage/image_test.go
> +func starLine(method drawingStraightLine, img Image, rgb RGB) {
сделала

2021-03-21 21:23 UTC, colleenbawn514 commented on pngimage/image_test.go
> +	y0 = 100 // The coordinate of the origin point for drawing a star (by Y).
сделала

2021-03-21 21:24 UTC, colleenbawn514 commented on pngimage/image_test.go
> +}
сделала

2021-03-21 21:24 UTC, colleenbawn514 commented on examples/building_straight_lines_test.go
> +func starLine(method drawingStraightLine, img pngimage.Image, rgb pngimage.RGB) {
Надеюсь правильно поняла

2021-03-21 21:24 UTC, colleenbawn514 commented on examples/building_straight_lines_test.go
> +	y0 = 100 // The coordinate of the origin point for drawing a star (by Y).
сделала

2021-03-22 04:20 UTC, as30606552 commented on pngimage/image.go
> -func WhiteImage(width, height  int) *Image {
Оставим тогда интовые параметры

2021-03-22 16:03 UTC, as30606552 requested changes

2021-03-22 16:03 UTC, as30606552 commented on pngimage/image.go
> -
Удалила конструктор совсем? Зачем?

2021-03-22 16:03 UTC, as30606552 commented on pngimage/image.go
> +func WhiteImage(width, height int) Image  {
Лучше вернуть вызов конструктора и чтобы метод возвращал указатель - так можно будет избежать лишнего копирования. В других методах то же самое.

2021-03-22 16:04 UTC, as30606552 commented
Возможно лучше сделать, чтобы работа со структурой RGB велась не через указатели, а напрямую

2021-03-22 16:15 UTC, colleenbawn514 commented on pngimage/image.go
> -
Ахах, блин забыла, пока исправляла, вернула назад)

2021-03-22 16:15 UTC, colleenbawn514 commented on pngimage/image.go
> +func WhiteImage(width, height int) Image  {
Исправила

2021-03-22 19:03 UTC, merged